//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Inputs/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""537b1ad2-aec1-4d08-8fde-1e0ed535d832"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""eeeadbf3-9f08-4a3b-9f5b-0c2ab471c295"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""fdece363-3b93-46e7-96ac-ac5b7ee8749d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Blink"",
                    ""type"": ""Button"",
                    ""id"": ""41e9bc69-3cad-4d72-97e1-4037fd9af647"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lean Left"",
                    ""type"": ""Button"",
                    ""id"": ""eb92ed48-754e-4cf5-a612-abdbddab28fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Lean Right"",
                    ""type"": ""Button"",
                    ""id"": ""a12672c4-b71c-4567-b93f-0aa434f913b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Watch"",
                    ""type"": ""Button"",
                    ""id"": ""a273a7cb-6764-4ef8-89b2-c948caca40d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""d4bec702-92b9-4903-954c-c1cf7cb5c824"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""65c9c1bb-05d9-44bf-848a-b2cc8f4a4304"",
                    ""path"": ""3DVector(mode=1)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""4afa8274-4af1-463f-b0fb-c83c5d2ee5e8"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""069da06e-c7b4-472a-8874-6f7d60995d33"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f873f3a1-018b-4918-a9c0-a0ad7e628169"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4507dfc4-f852-43d6-a3a3-7fe615bd2b7e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""7c7b74f4-977e-4176-b649-af9bb923e9ea"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""7c54a170-ab9f-4053-b4bc-fa6a549185e8"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f8013edb-1dd1-4114-8e98-271e7abc3278"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab4d31a3-c12a-4c34-b90b-35918b52c9d0"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Blink"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c0a4ec8-9e5a-4a90-96c0-57ae20360ec5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Lean Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29b0ff2-a584-43b8-9378-60a12e3a98b3"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Lean Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a4658ea-6523-41b3-8fed-421119cfb7d4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Watch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f901102e-209a-49a7-a2ba-9c5dc01c1817"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""1c8bd334-eed4-4f7f-9416-e052848e2a9d"",
            ""actions"": [
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""797b3db3-b412-4c87-939a-0984be988994"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Debug Info"",
                    ""type"": ""Button"",
                    ""id"": ""6c22de17-b1fd-4c9b-8848-6cc61f479c2f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""072b1eb2-07c3-49aa-a419-0a6f064e35b8"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5b87047-55bf-469e-b5e0-2491bf01b587"",
                    ""path"": ""<Keyboard>/f3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Debug Info"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Debug"",
            ""id"": ""1df2cf36-bebc-47c7-bf26-9a2733938024"",
            ""actions"": [
                {
                    ""name"": ""Haunt - Lights Off"",
                    ""type"": ""Button"",
                    ""id"": ""0ecf11a3-be1c-49f8-9e17-b15292b96e9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Haunt - Clock Chime"",
                    ""type"": ""Button"",
                    ""id"": ""521e6f42-0a40-4c46-986d-8f4b5e5ad032"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Haunt - TV On"",
                    ""type"": ""Button"",
                    ""id"": ""80c159f2-0e8f-41c0-90c3-d300602b2a3a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn - Father"",
                    ""type"": ""Button"",
                    ""id"": ""e20c0b1f-750b-4acf-84c6-7304024c7f84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn - Mother"",
                    ""type"": ""Button"",
                    ""id"": ""a304490c-dc10-4723-8e41-43845ed560ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Spawn - Daughter"",
                    ""type"": ""Button"",
                    ""id"": ""f11c8757-a7a1-4496-9a3e-b1d50f22f1a3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cheat - Sleep"",
                    ""type"": ""Button"",
                    ""id"": ""2e56e937-fb3d-498d-a0af-79cdc7d35195"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""d673d025-4d2a-49bf-9d0c-f2234bd9bfce"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Haunt - Lights Off"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""930b1b2e-2782-4451-ae0f-51f5ee468e41"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Haunt - Clock Chime"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""cb6efc1d-0593-4509-b313-d21c258cef9e"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn - Father"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""55d2f48e-5bc2-4381-8436-de29953711cc"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Spawn - Father"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""69f7bdf3-a356-49a7-9e3d-4337d0b7e321"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Spawn - Father"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""9c1b3a91-cae6-4bf5-a069-cec221dbe152"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn - Mother"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""f004d8b8-8036-4d4a-aa7b-082faf8afcaf"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Spawn - Mother"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""bbd987d7-7982-417c-9bd0-2ac924212577"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Spawn - Mother"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""21531326-98ad-4bf5-8064-bba8537641f7"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Spawn - Daughter"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""e0d97686-2f36-450b-978a-16623e749cd7"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Spawn - Daughter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""04e42c62-5faa-4e77-9949-8f787027c81e"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Spawn - Daughter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9a54e277-b02a-4e8b-b85a-90d33f3c74a0"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Haunt - TV On"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""729ee542-e9b5-47c9-9836-0242d5ef3855"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cheat - Sleep"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""bb991000-c2d0-43b4-97a9-3dc0fddc253b"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Cheat - Sleep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7c4a0d08-be8d-489e-a32d-2ecd93235e16"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Cheat - Sleep"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Blink = m_Player.FindAction("Blink", throwIfNotFound: true);
        m_Player_LeanLeft = m_Player.FindAction("Lean Left", throwIfNotFound: true);
        m_Player_LeanRight = m_Player.FindAction("Lean Right", throwIfNotFound: true);
        m_Player_Watch = m_Player.FindAction("Watch", throwIfNotFound: true);
        m_Player_Interact = m_Player.FindAction("Interact", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Pause = m_UI.FindAction("Pause", throwIfNotFound: true);
        m_UI_DebugInfo = m_UI.FindAction("Debug Info", throwIfNotFound: true);
        // Debug
        m_Debug = asset.FindActionMap("Debug", throwIfNotFound: true);
        m_Debug_HauntLightsOff = m_Debug.FindAction("Haunt - Lights Off", throwIfNotFound: true);
        m_Debug_HauntClockChime = m_Debug.FindAction("Haunt - Clock Chime", throwIfNotFound: true);
        m_Debug_HauntTVOn = m_Debug.FindAction("Haunt - TV On", throwIfNotFound: true);
        m_Debug_SpawnFather = m_Debug.FindAction("Spawn - Father", throwIfNotFound: true);
        m_Debug_SpawnMother = m_Debug.FindAction("Spawn - Mother", throwIfNotFound: true);
        m_Debug_SpawnDaughter = m_Debug.FindAction("Spawn - Daughter", throwIfNotFound: true);
        m_Debug_CheatSleep = m_Debug.FindAction("Cheat - Sleep", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Blink;
    private readonly InputAction m_Player_LeanLeft;
    private readonly InputAction m_Player_LeanRight;
    private readonly InputAction m_Player_Watch;
    private readonly InputAction m_Player_Interact;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Blink => m_Wrapper.m_Player_Blink;
        public InputAction @LeanLeft => m_Wrapper.m_Player_LeanLeft;
        public InputAction @LeanRight => m_Wrapper.m_Player_LeanRight;
        public InputAction @Watch => m_Wrapper.m_Player_Watch;
        public InputAction @Interact => m_Wrapper.m_Player_Interact;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Crouch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCrouch;
                @Blink.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlink;
                @Blink.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlink;
                @Blink.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlink;
                @LeanLeft.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeanLeft;
                @LeanLeft.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeanLeft;
                @LeanLeft.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeanLeft;
                @LeanRight.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeanRight;
                @LeanRight.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeanRight;
                @LeanRight.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLeanRight;
                @Watch.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWatch;
                @Watch.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWatch;
                @Watch.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnWatch;
                @Interact.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnInteract;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Blink.started += instance.OnBlink;
                @Blink.performed += instance.OnBlink;
                @Blink.canceled += instance.OnBlink;
                @LeanLeft.started += instance.OnLeanLeft;
                @LeanLeft.performed += instance.OnLeanLeft;
                @LeanLeft.canceled += instance.OnLeanLeft;
                @LeanRight.started += instance.OnLeanRight;
                @LeanRight.performed += instance.OnLeanRight;
                @LeanRight.canceled += instance.OnLeanRight;
                @Watch.started += instance.OnWatch;
                @Watch.performed += instance.OnWatch;
                @Watch.canceled += instance.OnWatch;
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Pause;
    private readonly InputAction m_UI_DebugInfo;
    public struct UIActions
    {
        private @Controls m_Wrapper;
        public UIActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Pause => m_Wrapper.m_UI_Pause;
        public InputAction @DebugInfo => m_Wrapper.m_UI_DebugInfo;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Pause.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPause;
                @DebugInfo.started -= m_Wrapper.m_UIActionsCallbackInterface.OnDebugInfo;
                @DebugInfo.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnDebugInfo;
                @DebugInfo.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnDebugInfo;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @DebugInfo.started += instance.OnDebugInfo;
                @DebugInfo.performed += instance.OnDebugInfo;
                @DebugInfo.canceled += instance.OnDebugInfo;
            }
        }
    }
    public UIActions @UI => new UIActions(this);

    // Debug
    private readonly InputActionMap m_Debug;
    private IDebugActions m_DebugActionsCallbackInterface;
    private readonly InputAction m_Debug_HauntLightsOff;
    private readonly InputAction m_Debug_HauntClockChime;
    private readonly InputAction m_Debug_HauntTVOn;
    private readonly InputAction m_Debug_SpawnFather;
    private readonly InputAction m_Debug_SpawnMother;
    private readonly InputAction m_Debug_SpawnDaughter;
    private readonly InputAction m_Debug_CheatSleep;
    public struct DebugActions
    {
        private @Controls m_Wrapper;
        public DebugActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @HauntLightsOff => m_Wrapper.m_Debug_HauntLightsOff;
        public InputAction @HauntClockChime => m_Wrapper.m_Debug_HauntClockChime;
        public InputAction @HauntTVOn => m_Wrapper.m_Debug_HauntTVOn;
        public InputAction @SpawnFather => m_Wrapper.m_Debug_SpawnFather;
        public InputAction @SpawnMother => m_Wrapper.m_Debug_SpawnMother;
        public InputAction @SpawnDaughter => m_Wrapper.m_Debug_SpawnDaughter;
        public InputAction @CheatSleep => m_Wrapper.m_Debug_CheatSleep;
        public InputActionMap Get() { return m_Wrapper.m_Debug; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DebugActions set) { return set.Get(); }
        public void SetCallbacks(IDebugActions instance)
        {
            if (m_Wrapper.m_DebugActionsCallbackInterface != null)
            {
                @HauntLightsOff.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntLightsOff;
                @HauntLightsOff.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntLightsOff;
                @HauntLightsOff.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntLightsOff;
                @HauntClockChime.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntClockChime;
                @HauntClockChime.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntClockChime;
                @HauntClockChime.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntClockChime;
                @HauntTVOn.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntTVOn;
                @HauntTVOn.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntTVOn;
                @HauntTVOn.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnHauntTVOn;
                @SpawnFather.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnFather;
                @SpawnFather.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnFather;
                @SpawnFather.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnFather;
                @SpawnMother.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnMother;
                @SpawnMother.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnMother;
                @SpawnMother.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnMother;
                @SpawnDaughter.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnDaughter;
                @SpawnDaughter.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnDaughter;
                @SpawnDaughter.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnSpawnDaughter;
                @CheatSleep.started -= m_Wrapper.m_DebugActionsCallbackInterface.OnCheatSleep;
                @CheatSleep.performed -= m_Wrapper.m_DebugActionsCallbackInterface.OnCheatSleep;
                @CheatSleep.canceled -= m_Wrapper.m_DebugActionsCallbackInterface.OnCheatSleep;
            }
            m_Wrapper.m_DebugActionsCallbackInterface = instance;
            if (instance != null)
            {
                @HauntLightsOff.started += instance.OnHauntLightsOff;
                @HauntLightsOff.performed += instance.OnHauntLightsOff;
                @HauntLightsOff.canceled += instance.OnHauntLightsOff;
                @HauntClockChime.started += instance.OnHauntClockChime;
                @HauntClockChime.performed += instance.OnHauntClockChime;
                @HauntClockChime.canceled += instance.OnHauntClockChime;
                @HauntTVOn.started += instance.OnHauntTVOn;
                @HauntTVOn.performed += instance.OnHauntTVOn;
                @HauntTVOn.canceled += instance.OnHauntTVOn;
                @SpawnFather.started += instance.OnSpawnFather;
                @SpawnFather.performed += instance.OnSpawnFather;
                @SpawnFather.canceled += instance.OnSpawnFather;
                @SpawnMother.started += instance.OnSpawnMother;
                @SpawnMother.performed += instance.OnSpawnMother;
                @SpawnMother.canceled += instance.OnSpawnMother;
                @SpawnDaughter.started += instance.OnSpawnDaughter;
                @SpawnDaughter.performed += instance.OnSpawnDaughter;
                @SpawnDaughter.canceled += instance.OnSpawnDaughter;
                @CheatSleep.started += instance.OnCheatSleep;
                @CheatSleep.performed += instance.OnCheatSleep;
                @CheatSleep.canceled += instance.OnCheatSleep;
            }
        }
    }
    public DebugActions @Debug => new DebugActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnBlink(InputAction.CallbackContext context);
        void OnLeanLeft(InputAction.CallbackContext context);
        void OnLeanRight(InputAction.CallbackContext context);
        void OnWatch(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnPause(InputAction.CallbackContext context);
        void OnDebugInfo(InputAction.CallbackContext context);
    }
    public interface IDebugActions
    {
        void OnHauntLightsOff(InputAction.CallbackContext context);
        void OnHauntClockChime(InputAction.CallbackContext context);
        void OnHauntTVOn(InputAction.CallbackContext context);
        void OnSpawnFather(InputAction.CallbackContext context);
        void OnSpawnMother(InputAction.CallbackContext context);
        void OnSpawnDaughter(InputAction.CallbackContext context);
        void OnCheatSleep(InputAction.CallbackContext context);
    }
}
